version: "3"
services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: cohee1207/sillytavern:latest
    ports:
      - "8006:8000"
    volumes:
      - "/srv/dev-disk-by-uuid-3db1486a-88a7-4237-9715-9d88c6ae4ab5/storage/Programs/Tavern/config:/home/node/app/config"
      - "/srv/dev-disk-by-uuid-3db1486a-88a7-4237-9715-9d88c6ae4ab5/storage/Programs/Tavern/config.conf:/home/node/app/config.conf"
    restart: unless-stopped